Sprint4
ClevertecFrontendLab/TatyanaZahozhaya pull request #2
Opened 2023-02-23 23:47 UTC by TatyanaZahozhaya

2023-02-23 23:52 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 93%.
Общее количество тестов: 16.
Количество непройденных тестов: 1.
***
**active-category-programming.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatyanaZahozhaya/1677196360/active-category-programming.png)
***
**bread crumbs -- tablet -- transfer from all books category to book page (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatyanaZahozhaya/1677196360/bread%20crumbs%20--%20tablet%20--%20transfer%20from%20all%20books%20category%20to%20book%20page%20(failed).png)
***
**clearing-search-input.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatyanaZahozhaya/1677196360/clearing-search-input.png)
***
**empty-category.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatyanaZahozhaya/1677196360/empty-category.png)
***
**find-books.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatyanaZahozhaya/1677196360/find-books.png)
***
**search-result-not-found.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatyanaZahozhaya/1677196360/search-result-not-found.png)

2023-02-24 06:23 UTC, vvikota requested changes

2023-02-24 06:23 UTC, vvikota commented on package.json
>      "redux": "^4.2.1",
![image](https://user-images.githubusercontent.com/30027067/221106409-b94ce1ab-bbc1-4e10-bfeb-a0f38d35fc04.png)
тут поломалось) нужно в одну строку по макету

2023-02-24 06:23 UTC, vvikota commented on package.json
>      "redux-persist": "^6.0.0",
![image](https://user-images.githubusercontent.com/30027067/221106548-28257e88-120b-49ff-81a6-4acd7c461b8c.png)
если книг меньше 4-х то центруем по левому краю

2023-02-24 06:23 UTC, vvikota commented on src/shared/components/navigation/index.tsx
> +        onClick={() => {
тут если не одно действие то можно выносить вверх компонента в функцию

2023-02-24 14:34 UTC, merged